import { HomeComponent } from './home.component';

// Generated by CodiumAI

describe('HomeComponent', () => {

  // Tests that the socialLinks array is populated with correct data
  it('should populate socialLinks array with correct data', () => {
    // Arrange
    const component = new HomeComponent();
    const expectedSocialLinks = [
      { title: 'Email', icon: '../../../assets/images/gmail.png', url: 'mailto:jsojhor@gmail.com.com' },
      { title: 'GitHub', icon: '../../../assets/images/github.png', url: 'https://github.com/jhorman10' },
      { title: 'LinkedIn', icon: '../../../assets/images/linkedin.png', url: 'https://www.linkedin.com/in/jhorman-orozco/' },
      { title: 'WhatsApp', icon: '../../../assets/images/whatsapp.png', url: 'https://wa.me/573007020377' }
    ];

    // Act
    const actualSocialLinks = component.socialLinks;

    // Assert
    expect(actualSocialLinks).toEqual(expectedSocialLinks);
  });
});

